"""ProductProfile — the central data model.

This is the intermediate representation generated by heuristic analysis
(Phase 1) and enriched by Cursor-assisted deep analysis (Phase 2).
All rule generators, hook generators, and onboarding generators
read from this model.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from pydantic import BaseModel, Field

from product_builders.models.analysis import (
    APIResult,
    AccessibilityResult,
    AnalysisResult,
    ArchitectureDeepResult,
    AuthResult,
    CICDResult,
    ConventionsResult,
    DatabaseResult,
    DependenciesResult,
    DesignUIResult,
    DomainModelDeepResult,
    EnvConfigResult,
    ErrorHandlingResult,
    GitWorkflowResult,
    I18nResult,
    ImplicitConventionsDeepResult,
    PerformanceResult,
    SecurityResult,
    StateManagementResult,
    StructureResult,
    TechStackResult,
    TestingResult,
)
from product_builders.models.scopes import ScopeConfig


class ProductMetadata(BaseModel):
    """Metadata about the analyzed product."""

    name: str = Field(min_length=1)
    description: str = ""
    repo_path: str = ""
    repo_url: str = ""
    git_platform: str | None = None
    sub_project: str | None = None
    analysis_timestamp: datetime = Field(
        default_factory=lambda: datetime.now(tz=timezone.utc)
    )
    analysis_version: str = "0.1.0"
    last_commit_sha: str | None = None
    product_family: str | None = None


class ProductProfile(BaseModel):
    """Complete product profile — all 18 dimensions + deep analysis + scopes.

    This is the single source of truth from which all outputs are generated:
    - 14 Cursor rule files (.mdc)
    - hooks.json (Layer 2)
    - cli.json (Layer 3)
    - Onboarding guide
    - Review checklist
    - Team Rules recommendations
    """

    metadata: ProductMetadata

    # CRITICAL — Can cause data loss or security breaches
    tech_stack: TechStackResult = Field(default_factory=TechStackResult)
    database: DatabaseResult = Field(default_factory=DatabaseResult)
    auth: AuthResult = Field(default_factory=AuthResult)

    # HIGH IMPACT — Breaks production functionality
    dependencies: DependenciesResult = Field(default_factory=DependenciesResult)
    error_handling: ErrorHandlingResult = Field(default_factory=ErrorHandlingResult)
    i18n: I18nResult = Field(default_factory=I18nResult)
    state_management: StateManagementResult = Field(default_factory=StateManagementResult)
    env_config: EnvConfigResult = Field(default_factory=EnvConfigResult)
    git_workflow: GitWorkflowResult = Field(default_factory=GitWorkflowResult)

    # MEDIUM IMPACT — Quality and compliance
    structure: StructureResult = Field(default_factory=StructureResult)
    conventions: ConventionsResult = Field(default_factory=ConventionsResult)
    security: SecurityResult = Field(default_factory=SecurityResult)
    testing: TestingResult = Field(default_factory=TestingResult)
    cicd: CICDResult = Field(default_factory=CICDResult)
    design_ui: DesignUIResult = Field(default_factory=DesignUIResult)
    accessibility: AccessibilityResult = Field(default_factory=AccessibilityResult)
    api: APIResult = Field(default_factory=APIResult)
    performance: PerformanceResult = Field(default_factory=PerformanceResult)

    # DEEP — Populated by Cursor-assisted analysis (Phase 2)
    architecture_deep: ArchitectureDeepResult = Field(
        default_factory=ArchitectureDeepResult
    )
    domain_model_deep: DomainModelDeepResult = Field(
        default_factory=DomainModelDeepResult
    )
    implicit_conventions_deep: ImplicitConventionsDeepResult = Field(
        default_factory=ImplicitConventionsDeepResult
    )

    # Scope configuration
    scopes: ScopeConfig = Field(default_factory=ScopeConfig)

    def save(self, path: Path) -> None:
        """Serialize profile to JSON file."""
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(self.model_dump_json(indent=2), encoding="utf-8")

    @classmethod
    def load(cls, path: Path) -> ProductProfile:
        """Deserialize profile from JSON file."""
        return cls.model_validate_json(path.read_text(encoding="utf-8"))

    def get_analyzer_results(self) -> dict[str, AnalysisResult]:
        """Return a dict of dimension name → analysis result for iteration."""
        return {
            "tech_stack": self.tech_stack,
            "database": self.database,
            "auth": self.auth,
            "dependencies": self.dependencies,
            "error_handling": self.error_handling,
            "i18n": self.i18n,
            "state_management": self.state_management,
            "env_config": self.env_config,
            "git_workflow": self.git_workflow,
            "structure": self.structure,
            "conventions": self.conventions,
            "security": self.security,
            "testing": self.testing,
            "cicd": self.cicd,
            "design_ui": self.design_ui,
            "accessibility": self.accessibility,
            "api": self.api,
            "performance": self.performance,
        }
